-- MySQL Script generated by MySQL Workbench
-- Wed Dec  1 13:55:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `password` VARCHAR(45) NOT NULL,
                                             `email` VARCHAR(45) NOT NULL,
                                             `name` VARCHAR(45) NOT NULL,
                                             `surname` VARCHAR(45) NOT NULL,
                                             `phone_num` VARCHAR(45) NOT NULL,
                                             `role` ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER',
                                             `status` ENUM('BLOCKED', 'UNBLOCKED') NOT NULL DEFAULT 'UNBLOCKED',
                                             PRIMARY KEY (`id`),
                                             UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 29
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `name` VARCHAR(45) NOT NULL,
                                                `status` ENUM('BLOCKED', 'OPEN') NOT NULL DEFAULT 'OPEN',
                                                `number` VARCHAR(45) NOT NULL,
                                                `balance` DECIMAL(9,2) NOT NULL DEFAULT '0.00',
                                                `user_id` INT NOT NULL,
                                                PRIMARY KEY (`id`),
                                                UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
                                                INDEX `fk_account_user_idx` (`user_id` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 32
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `status` ENUM('NEW', 'DONE') NOT NULL DEFAULT 'NEW',
                                                `date` DATETIME NOT NULL,
                                                `amount` DECIMAL(9,2) NOT NULL,
                                                `account_id` INT NOT NULL,
                                                PRIMARY KEY (`id`),
                                                INDEX `fk_payment_account1_idx` (`account_id` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 32
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`payment_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment_card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment_card` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `card_number` VARCHAR(16) NOT NULL,
                                                     `expiration` DATE NOT NULL,
                                                     `cvc_code` INT NOT NULL,
                                                     `account_id` INT NOT NULL,
                                                     PRIMARY KEY (`id`),
                                                     UNIQUE INDEX `number_card_UNIQUE` (`card_number` ASC) VISIBLE,
                                                     INDEX `fk_payment_card_account1_idx` (`account_id` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 22
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`request_unblock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`request_unblock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`request_unblock` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `status` ENUM('NEW', 'DONE') NOT NULL DEFAULT 'NEW',
                                                        `account_id` INT NOT NULL,
                                                        PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 120
    DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



